import { HttpClientResponse } from "@core/models";

export interface Product {
    productId: number,
    productCode: string,
    name1: string,
    standardInfo: string,
    categoryCode1: string,
    categoryCode2: string,
    categoryCode3: string,
    categoryCode4: string,
    categoryCode5: string,
    notes: string,
    fifoType: string,
    isDatetimeMng: string,
    datetimeMngType: string,
    isNumberMng: string,
    isPackCsInput: string,
    isPackCsOutput: string,
    packCsUnitCode: string,
    packCsUnitName: string,
    packCsAmount: number,
    isPackBlInput: string,
    isPackBlOutput: string,
    packBlUnitCode: string,
    packBlUnitName: string,
    packBlAmount: string,
    isPieceInput: string,
    isPieceOutput: string,
    pieceUnitCode: string,
    pieceUnitName: string,
    repositoryId: number,
    repositoryCode: string,
    locationId: number,
    locationCode: string,
    isReplenishMng: string,
    minInventoryQuantity: number,
    minInputQuantity: number,
    isVarious: string,
    supplierId: number,
    supplierCode: string,
    leadTime: string,
    tax: string,
    isSet: string,
}
export interface HttpProductResponse extends HttpClientResponse {
    data: Product;
}
