import { FormControl } from '@angular/forms';

export const formOutputList = {
  page: new FormControl(null),
  size: new FormControl(null),
  repositoryIdFrom: new FormControl(null),
  repositoryIdTo: new FormControl(null),
  orderDateFrom: new FormControl(null),
  orderDateTo: new FormControl(null),
  planOutputDateFrom: new FormControl(null),
  planOutputDateTo: new FormControl(null),
  planWorkingDateFrom: new FormControl(null),
  planWorkingDateTo: new FormControl(null),
  planDeliverDateFrom: new FormControl(null),
  planDeliverDateTo: new FormControl(null),
  slipNoFrom: new FormControl(null),
  slipNoTo: new FormControl(null),
  productCodeFrom: new FormControl(null),
  productCodeTo: new FormControl(null),
  batchNo: new FormControl(null),
  productName: new FormControl(null),
  destinationCodeFrom: new FormControl(null),
  destinationCodeTo: new FormControl(null),
  departmentName: new FormControl(null),
  supplierCodeFrom: new FormControl(null),
  supplierCodeTo: new FormControl(null),
  supplierName: new FormControl(null),
  customerCodeFrom: new FormControl(null),
  customerCodeTo: new FormControl(null),
  customerName: new FormControl(null),
  ownerCodeForm: new FormControl(null),
  ownerCodeTo: new FormControl(null),
  DeliveryType: new FormControl("0"),
  DeliveryStatus: new FormControl("0"),
  isClosed: new FormControl("2"),
};
